### ISSUE TITLE
Reimplemented singer-python function

### ISSUE THREAD

**Issue by luandy64** [MeowWolf/tap-appfigures#1]
https://github.com/MeowWolf/tap-appfigures/blob/c6172f652764c7db67d46ce4db95c37c609dcf6e/tap_appfigures/__init__.py#L78

Can this function be replaced with [this function](https://github.com/singer-io/singer-python/blob/4b652e7a7c224ce621d86dd1c54b47d4c20d5ba9/singer/utils.py#L126-L180)?

**Comment by CompassMentis** [comment]
Done. See https://github.com/MeowWolf/tap-appfigures/blob/338619e09efa8e0c874c96876604e696777166d6/tap_appfigures/__init__.py#L23
