### ISSUE TITLE
README Inaccuracy 

### ISSUE THREAD

**Issue by luandy64** [MeowWolf/tap-appfigures#2]
> The --state is a required parameter.
>
> Do not create the file (typically) state.json yourself. The script will create it on the first run

Do you mean : 
- the `config.json ` is required
- the `state.json` is optional
- do not create the `catalog.json` file yourself because the tap will create it on the first run if you run it like this:

```
~/.virtualenvs/tap-appfigures/bin/tap-appfigures --config config.json > ./catalog.json
```
[More information](https://github.com/singer-io/getting-started/blob/master/docs/DISCOVERY_MODE.md#discovery-mode)

**Comment by CompassMentis** [comment]
Done. See https://github.com/MeowWolf/tap-appfigures/blob/master/tap_appfigures/README.md

Please note that the catalog is not really used in this tap. For instance, you cannot use the catalog to only extract part of the data
