### ISSUE TITLE
Use raise_for_status

### ISSUE THREAD

**Issue by luandy64** [MeowWolf/tap-appfigures#3]
I like that there is exception handling when you make requests, but to be thorough, let's also use the `requests` library's `raise_for_status()` function.

[See this example](https://github.com/singer-io/tap-jira/blob/bed80f34b4373ff3d1632af572ff1b0ddc5c5b94/tap_jira/http.py#L116)

**Comment by CompassMentis** [comment]
Good point. Added. See https://github.com/MeowWolf/tap-appfigures/blob/338619e09efa8e0c874c96876604e696777166d6/tap_appfigures/client.py#L51
