### ISSUE TITLE
state.py

### ISSUE THREAD

**Issue by luandy64** [MeowWolf/tap-appfigures#4]
Why not use the `singer-python` functions?
- https://github.com/singer-io/singer-python/blob/4b652e7a7c224ce621d86dd1c54b47d4c20d5ba9/singer/messages.py#L263
- https://github.com/singer-io/singer-python/blob/4b652e7a7c224ce621d86dd1c54b47d4c20d5ba9/singer/bookmarks.py#L10
- etc.

**Comment by CompassMentis** [comment]
Because I was writing the state back to the state file, and the existing functions didn't support that very well, so I wrote some replacements. I now know that a tap is not supposed to update the state file directly. So the code now uses the standard singer-python functions
